### ISSUE TITLE
Setup CLA

### ISSUE THREAD

**Issue by josh** [github/codemirror-contrib#1]
https://cla.github.com/

**Comment by larshp** [comment]
I have submitted the first PR, any news on the CLA setup?

**Comment by josh** [comment]
@bkeepers hey! how do I register new repositories with [GitHub CLA](https://cla.github.com/)?

**Comment by bkeepers** [comment]
@josh I pinged you in chat and ran the chatops command to enable it.

cc @mlinksva

**Comment by josh** [comment]
@bkeepers ❤️ 

Confirmed working on PR https://github.com/github/codemirror-contrib/pull/4
