### ISSUE TITLE
ABAP mode

### ISSUE THREAD

**Issue by larshp** [github/codemirror-contrib#2]
I can add the code from my `codemirror-abap` project, after the CLA(#1) has been setup.

Guess the preferred language will be JavaScript, so I'll convert my TypeScript to Javascript(manually).

Suggest folder structure as /mode/abap/

Also need to consider an approach for unit testing

**Comment by josh** [comment]
For the most part I'd like to follow whatever https://github.com/codemirror/CodeMirror itself is using as coding conventions. That would likely increase the chances of it being moved to the @codemirror org someday.

CodeMirror is using rollup/es6 modules for its code build, but not addons and modes yet. But I'd actually like to figure that out. @github's build system prefers ES6 modules but we use an AMD loader for *legacy* packages.
